```{r}

outlier<- function(x) {
 
    ifelse(x<(quantile(x,.25)-((quantile(x,.75)-quantile(x,.25))*1.5)),x,ifelse(x>(quantile(x,.75)+((quantile(x,.75)-quantile(x,.25))*1.5)),x,"Not an Outlier"))
    
    
  }


w<-c(5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,-1000,1000)

outlier(w)
```

```{r}

```


```{r}
digitToWord<- function(x){
 ifelse(x=="1","one",ifelse(x=="2","two",ifelse(x=="3","three",ifelse(x=="4","four",ifelse(x=="5","five",ifelse(x=="6","six",ifelse(x=="7","seven",ifelse(x=="8","eight",ifelse(x=="9","nine","Needs to be between 0 and 10")))))))))
}

digitToWord(1)
digitToWord(2)

digitToWord(9)
digitToWord(11)
```

```{r}
digitToWord2 <- function(language, number) {
  if(language == "english") {
    if(number == "0"){ 
      print("zero")
    }
    if(number == "1"){
      print("one")
    }
    if(number == "2"){
      print("two")
    }
    if(number == "3"){
      print("three")
    }
    if(number =="4"){
      print("four")
    }
    if(number =="5"){
      print("five")
    }
    if(number =="6"){
      print("six")
    }
    if(number =="7"){
      print("seven")
    }
    if(number =="8"){
      print("eight")
    }
    if(number =="9"){
      print("nine")
    }
    }
  if(language == "spanish") {
    if(number =="0"){
      print("cero")
    }
    if(number =="1"){
      print("uno")
    }
    if(number =="2"){
      print("dos")
    }
    if(number =="3"){
      print("tres")
    }
    if(number =="4"){
      print("cuatro")
    }
    if(number =="5"){
      print("cinco")
    }
    if(number =="6"){
      print("seis")
    }
    if(number =="7"){
      print("siete")
    }
    if(number =="8"){
      print("ocho")
    }
    if(number =="9"){
      print("nueve")
    }
  }
  if(language == "french") {
    if(number =="0"){
      print("zero")
    }
    if(number =="1"){
      print("un")
    }
    if(number =="2"){
      print("deux")
    }
    if(number =="3"){
      print("trois")
    }
    if(number =="4"){
      print("quartre")
    }
    if(number =="5"){
      print("cinq")
    }
    if(number =="6"){
      print("six")
    }
    if(number =="7"){
      print("sept")
    }
    if(number =="8"){
      print("huit")
    }
    if(number =="9"){
      print("neuf")
    }
}
  }

digitToWord2("english","2")
digitToWord2("spanish","5")
digitToWord2("french","7")
```

```{r}
lettersMatch<-function(x,y){
  grepl(x,y)
}
q<-c("word","names","twelve","wonder","hungry","slow","am","find","eighteen","search")
lettersMatch("^...$",q)
grepl("^....$",q)
```

```{r}
lettersMatch2 <- function(words, pattern) {
  list <- grepl(pattern, words)
  return(list)
}
q<-c("word","names","twelve","wonder","hungry","slow","am","find","eighteen","search")
lettersMatch2(q, "^....$")
```


```{r}
piSeries<-function(n){
  return(4*(sum(((1/(((((1:n)-1)*2)+1)))*(-1)^((1:n)-1)))))
}
piSeries(5)
piSeries(10)
piSeries(100000)
howCloseToPi<-function(n){
  plot((4*(cumsum(((1/(((((1:n)-1)*2)+1)))*(-1)^((1:n)-1))))))
}
howCloseToPi(1000)



randomApproxToPi<-function(n){
  x<-runif(100)
  y<-runif(100)
  q<-(x^2)+(y^2)
 plot(sapply(q,howCloseToPi))
}

randomApproxToPi(10)
```


```{r}
randomApproxToPi2<-function(n){
  sapply(10^runif(100,min=2,max=6),howCloseToPi)
}
sapply(10^runif(1,min=2,max=6),howCloseToPi)
```
 plot(((x^2)+(y^2)))